@startuml

digraph G {
  rankdir="TB";
  nojustify=false;
  node [shape=plaintext, fontname="Arial" fontsize="8", align="left"];

subgraph cluster_legend {
  peripheries=1
  label="Legend" 
  
  // Security Objective Node
  "security_objective" [fillcolor="#bae9ff", style=filled, shape=ellipse, color="#2bbcff", label=
    <<table border="0" cellborder="0" cellspacing="0">
     <tr><td align="center"><b>Security Objective</b><br/>
     Description of the security objective
     </td></tr>
    </table>>]
    
  // Threat Node
  "threat" [fillcolor="#F8CECC", style=filled, shape=polygon, color="#B85450", label=
    <<table border="0" cellborder="0" cellspacing="0" width="150">
     <tr><td align="center"><b>THREAT ATTACK</b> <br/></td></tr>
     <tr><td align="center">Description of the threat</td></tr>
    </table>>]
  
  // Implemented Countermeasure Node
  "countermeasure_implemented" [fillcolor="#D5E8D4", style=filled, shape=polygon, color="#82B366", label=
    <<table border="0" cellborder="0" cellspacing="0" width="150">
     <tr><td align="left"><b>Implemented Countermeasure (ID)</b><br/><br/>Description of the countermeasure</td></tr>
    </table>>]
  
  // Planned Countermeasure Node
  "countermeasure_planned" [fillcolor="#FFF2CC", style=filled, shape=polygon, color="#D6B656", label=
    <<table border="0" cellborder="0" cellspacing="0" width="150">
     <tr><td align="left"><b>Planned Countermeasure (ID)</b><br/><br/>Description of the countermeasure</td></tr>
    </table>>]
  
  ' // Edges with relationships
  ' "countermeasure_implemented" -> "threat" [label = " mitigates"]
  ' "countermeasure_planned" -> "threat" [label = " mitigates"]
  ' "threat" -> "security_objective" [label = " impacts"]
    
  ' // Position nodes for better layout
  ' {rank=same; "countermeasure_implemented" "countermeasure_planned"}
  ' {rank=same; "threat" "security_objective"}
}
}
@enduml
