// AUTO-GENERATED by build-docusaurus-site.ts — do not edit manually

/** @type {import('@docusaurus/types').Config} */
module.exports = {
  title: 'Threat Models',
  tagline: 'Generated threat model documentation',
  url: 'http://localhost',
  baseUrl: '/',
    markdown: {
        format: 'md',
        hooks: {
            onBrokenMarkdownLinks: 'warn'
        }
    },
  onBrokenLinks: 'warn',
  trailingSlash: true,
  presets: [
    [
      'classic',
      {
        docs: {
          path: 'docs',
          routeBasePath: '/',
          sidebarPath: require.resolve('./sidebars.js')
        },
        blog: false,
        pages: false,
        sitemap: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css')
        }
      }
    ]
  ],
  themeConfig: {
    navbar: {
      title: 'Threat Models',
      items: [
        { to: '/', label: 'Home', position: 'left' },
        { to: '/example1/', label: 'Abstract Example Threat Model', position: 'left' },
        { to: '/example2/', label: 'Abstract Example Threat Model 2', position: 'left' },
        { to: '/fullfeature/', label: 'Comprehensive Reference TM', position: 'left' },
      ]
    }
  },
  scripts: [
    {
      src: '/js/tm.js',
      defer: true
    }
  ]
};
