@startuml

digraph G {
  rankdir="LR";
  nojustify=false;
  node [shape=plaintext, fontname="Arial" fontsize="8", align="left"];

subgraph cluster_legend {
  peripheries=1
  label="Legend" 
  

    rankdir="RL"; // Changed to LR for horizontal layout
    node [shape=plaintext, fontname="Arial" fontsize="8", align="left"];
    

  "Legend_ThreatTarget" [fillcolor="#bae9ff", style=filled, shape=ellipse, color="#B85450",
    label=<
    <table border="0" cellborder="0" cellspacing="0">
    <tr><td align="left"><b>Threat Target</b></td></tr>
    <tr><td align="left"><font point-size="8">Target of threats/attacks.</font></td></tr>
    </table>>
  ];

  "Legend_Threat" [fillcolor="#F8CECC", style=filled, shape=polygon, color="#B85450", penwidth=2,
    label=<
    <table border="0" cellborder="0" cellspacing="0" width="150">
    <tr><td align="left"><b>Threat</b></td><td BGCOLOR="#df3d03"><font point-size="8">Risk</font></td></tr>
    <tr><td align="center" COLSPAN="2"><font point-size="8">A potential event that can cause harm.</font></td></tr>
    </table>>
  ];

  "Legend_Mitigated_Threat" [fillcolor="#d3d3d3", style=filled, shape=polygon, color="#B85450", penwidth=2,
    label=<
    <table border="0" cellborder="0" cellspacing="0" width="150">
    <tr><td align="left"><b>Mitigated Threat</b></td><td BGCOLOR="#4CAF50"><font point-size="8">Mitigated</font></td></tr>
    <tr><td align="center" COLSPAN="2"><font point-size="8">A threat that has been fully addressed.</font></td></tr>
    </table>>
  ];

  "Legend_Mitigation_InPlace" [fillcolor="#D5E8D4", style=filled, shape=polygon, penwidth=2, color="#82B366",
    label=<
    <table border="0" cellborder="0" cellspacing="0" width="150">
    <tr><td align="left"><b>Existing Countermeasure</b></td></tr>
    <tr><td align="left"><font point-size="8">A control currently in place to mitigate a threat.</font></td></tr>
    </table>>
  ];

  "Legend_Mitigation_Proposed" [fillcolor="#FFF2CC", style=filled, shape=polygon, penwidth=2, color="#D6B656",
    label=<
    <table border="0" cellborder="0" cellspacing="0" width="150">
    <tr><td align="left"><b>Proposed Countermeasure</b></td></tr>
    <tr><td align="left"><font point-size="8">A possible control to mitigate a threat.</font></td></tr>
    </table>>
  ];



  "Legend_Line_Mitigates" [
    label=<
    <table border="0" cellborder="0" cellspacing="0">
    <tr><td align="left"><font color="green"><b>─────</b></font> Mitigates (Existing counter-measure)</td></tr>
    </table>>
  ];

  "Legend_Line_Impacts" [
    label=<
    <table border="0" cellborder="0" cellspacing="0">
    <tr><td align="left"><font color="#B85450"><b>─────</b></font> Impacts (Threat to Group)</td></tr>
    </table>>
  ];

  "Legend_Line_Proposed" [
    label=<
    <table border="0" cellborder="0" cellspacing="0">
    <tr><td align="left"><font color="#B85450"><b>- - - -</b></font> Addresses (Proposed countermeasure)</td></tr>
    </table>>
  ];

  "Legend_Line_Mitigated" [
    label=<
    <table border="0" cellborder="0" cellspacing="0">
    <tr><td align="left"><font color="green"><b>- - - -</b></font> Mitigated (Threat to Group)</td></tr>
    </table>>
  ];
  // Add invisible edges to enforce horizontal order
  "Legend_ThreatTarget" -> "Legend_Threat" -> "Legend_Mitigated_Threat" -> "Legend_Mitigation_InPlace" -> "Legend_Mitigation_Proposed" -> "Legend_Line_Mitigates" -> "Legend_Line_Impacts" -> "Legend_Line_Proposed" -> "Legend_Line_Mitigated" [style=invis];

  ' // Position nodes for better layout
  ' {rank=same; "countermeasure_implemented" "countermeasure_planned"}
  ' {rank=same; "threat" "security_objective"}
   {rank=same;  "Legend_Line_Proposed" "Legend_Line_Mitigated"}
  {rank=same;  "Legend_Line_Mitigates" "Legend_Line_Impacts"}

    }
}
@enduml
