// @ts-check
// AUTO-GENERATED by build-astro-site.ts — do not edit manually
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  integrations: [
    starlight({
      title: 'Threat Models',
      customCss: [
        './src/styles/threatmodel.css',
      ],
      sidebar: [
        { label: 'Home', link: '/' },
        { label: 'Abstract Example Threat Model', link: '/example1/' },
        { label: 'Abstract Example Threat Model 2', link: '/example2/' },
        { label: 'Comprehensive Reference TM', link: '/fullfeature/' },
      ],
      head: [
        { tag: 'script', attrs: { src: '/js/tm.js', defer: true } },
        { tag: 'script', content: 'window.__TM_NAV_LINKS__ = [{"label":"Home","href":"/"},{"label":"Abstract Example Threat Model","href":"/example1/"},{"label":"Abstract Example Threat Model 2","href":"/example2/"},{"label":"Comprehensive Reference TM","href":"/fullfeature/"}]' },
      ],
    }),
  ],
  trailingSlash: 'always',
});
